import { Roboto } from 'next/font/google'
import './globals.css'
import { Header } from '../components/Layout/Header'
import { AppProvider } from '../components/AppContext'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={roboto.className} suppressHydrationWarning={true}>
        <main className='mx-auto max-w-4xl p-4'>
          <AppProvider>
            <Header />
            {children}
            <footer className='text-gray- mt-16 border-t p-8 text-center'>&copy; 2024 All Right is Wrong.</footer>
          </AppProvider>
        </main>
      </body>
    </html>
  )
}
